# Default values for spring-boot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

git:
  branch: master  
  # for projects based on maven modules, specify the top-level url in order to import the dependencies
  url: ""
  # for projects based on maven modules, builds the specified sub-module 
  module: ""
  
# specify a docker image if you don't want to build from source 
docker:
  image: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}

podAnnotations: {}

# default Spring Boot port, override to reflect server.port config
service:
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
