kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    {{- include "spring-boot.annotations" . | nindent 4 }}
  name: {{ .Chart.Name }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  {{ if .Values.image_name }}
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: '{{ .Values.docker.image }}'
      from:
        kind: DockerImage
        name: '{{ .Values.docker.image }}'
      generation: 9
      importPolicy: {}
      referencePolicy:
        type: Source
  {{ end }}