kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-{{ include "spring-boot.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
