{{- if .Values.serviceAccount.createRole -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-kube
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
{{- end }}