kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-spring-kube
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  apiGroup: ""
roleRef:
  kind: Role
  name: spring-kube
  apiGroup: ""