apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "spring-boot.fullname" . }}
spec:
  serviceAccountName: pipeline
  triggers:
  - interceptors:
    - cel:
        filter: >-
          (header.match('X-GitHub-Event', 'push') &&
          body.ref.startsWith('refs/heads/{{ .Values.git.branch }}'))
    bindings:
    - name: common-bindings
      ref: devopsinabox-github
    - name: message-binding
      spec:
        params:
          - name: app-name
            value: {{ include "spring-boot.fullname" . }}
          - name: image-repo
            value: {{ .Values.docker.repo }}
          - name: config-repo
            value: {{ .Values.config.repo }}
          - name: workspace
            value: workspace-{{ include "spring-boot.fullname" . }}
          - name: image-field-name
            value: "spec.docker.image"
    template:
      name: devopsinabox
  {{- if .Values.version.name }}
  {{- $top := . }}
  - interceptors:
    - cel:
        filter: >-
          (header.match('X-GitHub-Event', 'push') &&
          body.ref.startsWith('refs/heads/{{ .Values.version.branch }}'))
    bindings:
    - name: common-bindings
      ref: devopsinabox-github
    - name: message-binding
      spec:
        params:
          - name: app-name
            value: {{ include "spring-boot.fullname" . }}
          - name: image-repo
            value: {{ .Values.docker.repo }}
          - name: config-repo
            value: {{ .Values.config.repo }}
          - name: workspace
            value: workspace-{{ include "spring-boot.fullname" . }}
          - name: image-field-name
            value: "spec.version.image"
    template:
      name: devopsinabox
  {{- end }}