apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "spring-boot.fullname" . }}
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: common-bindings
      ref: devopsinabox-github
    - name: message-binding
      spec:
        params:
          - name: app-name
            value: {{ include "spring-boot.fullname" . }}
          - name: image-repo
            value: {{ .Values.docker.image }}
          - name: config-repo
            value: {{ .Values.config.repo }}
    template:
      name: devopsinabox