apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ include "spring-boot.fullname" . }}
spec:
  serviceAccountName: pipeline
  triggers:
  - interceptors:
    - cel:
        filter: >-
          (header.match('X-GitHub-Event', 'push') &&
          body.ref.startsWith('refs/heads/{{ .Values.git.branch }}'))
    bindings:
    - ref: devopsinabox-github
    - name: app-name
      value: {{ include "spring-boot.fullname" . }}
    - name: image-repo
      value: {{ .Values.container.registry }}
    - name: git-repo-url
      value: {{ .Values.git.url }}
    - name: config-repo
      value: {{ .Values.config.repo }}
    - name: dockerfile-repo
      value: {{ .Values.dockerfile.repo }}
    - name: workspace
      value: workspace-{{ include "spring-boot.fullname" . }}
    - name: image-field-name
      value: ".spec.container.image"
    template:
      ref: devopsinabox
  {{- if .Values.version.name }}
  {{- $top := . }}
  - interceptors:
    - cel:
        filter: >-
          (header.match('X-GitHub-Event', 'push') &&
          body.ref.startsWith('refs/heads/{{ .Values.version.branch }}'))
    bindings:
    - ref: devopsinabox-github
      - name: app-name
        value: {{ include "spring-boot.fullname" . }}
      - name: image-repo
        value: {{ .Values.container.registry }}
      - name: git-repo-url
        value: {{ .Values.git.url }}
      - name: config-repo
        value: {{ .Values.config.repo }}
      - name: workspace
        value: workspace-{{ include "spring-boot.fullname" . }}
      - name: image-field-name
        value: ".spec.version.image"
    template:
      name: devopsinabox
  {{- end }}